// Generated by CodiumAI

describe('Createuser', () => {

});

    // Tests that a user can be created when submitting the form with valid name, email and age
    it('should create a user when submitting the form with valid name, email and age', async () => {
        const response = await axios.post.mockResolvedValueOnce({ data: { name: 'John', email: 'john@example.com', age: 30 } });
        const { getByPlaceholderText, getByText } = render(<Createuser />);
        const nameInput = getByPlaceholderText('Your Name');
        const emailInput = getByPlaceholderText('Your Email');
        const ageInput = getByPlaceholderText('Your Age');
        fireEvent.change(nameInput, { target: { value: 'John' } });
        fireEvent.change(emailInput, { target: { value: 'john@example.com' } });
        fireEvent.change(ageInput, { target: { value: '30' } });
        fireEvent.click(getByText('Submit'));
        await waitFor(() => expect(axios.post).toHaveBeenCalledWith('http://localhost:5121/createUser', { name: 'John', email: 'john@example.com', age: '30' }));
        expect(getByText('Add User')).toBeInTheDocument();
    });

